server:
  port: 9090
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Spring
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  #main:
    web-application-type: none  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  #autoconfigure:
    exclude:
    -   
    
management:
  endpoints:
    web:
      exposure:
        include:
        -   "*"